
from building import *
import rtconfig

cwd     = GetCurrentDir()

src = Glob('*.c')
CPPPATH = [cwd]
LOCAL_CCFLAGS = ''

group = DefineGroup('zmod4410', src, depend = ['PKG_USING_ZMOD4410'], CPPPATH = CPPPATH, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
